Figlet no arguments test
cs50/problems pull request #276
Opened 2024-08-18 13:38 UTC by ZRexshima

I added a test to check the error code of figlet.py run without arguments.

There was not a test for exit code when running figlet.py without arguments. This is a requirement for the assignment that should randomly select a font, prompt for input, then output the ASCII art.

This is a replacement of PR #275. This time it only has the individual change.

2025-06-25 15:31 UTC, bxngyn reviewed
Thanks for submitting a PR!

In `test_no_arguments`, the `if` condition and the `raise` statement are mismatched. Also, I believe that since the program is waiting for the user's input, we should use `prompt=True`. Essentially, if `figlet.py` is ran without any args and a valid std input (expected behavior), then we would expect a successful exit code of `0`, but the `raise` statement doesn't match this expectation.

2025-06-26 06:26 UTC, rongxin-liu requested changes
Echoing @bxngyn, I think we can simply test whether running the program without interacting with it returns an exit code of 0. If it does, then the program fails the no arguments test, because it should exit with a non-zero code when no arguments are provided.

2025-06-26 22:59 UTC, ZRexshima commented
I changed the prompt argument to True and changed the messaging for clarity.

2025-06-27 17:58 UTC, rongxin-liu approved these changes

2025-06-27 17:58 UTC, rongxin-liu commented
Thank you!

2025-06-27 17:58 UTC, merged